export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_CLAIM_REQUEST = "GET_CLAIM_REQUEST";
export const GET_CLAIM_SUCCESS = "GET_CLAIM_SUCCESS";
export const GET_CLAIM_FAILURE = "GET_CLAIM_FAILURE";

export const ADD_CLAIM_REQUEST = "ADD_CLAIM_REQUEST";
export const ADD_CLAIM_FILE_SUCCESS = "ADD_CLAIM_FILE_SUCCESS";
export const ADD_CLAIM_FAILURE = "ADD_CLAIM_FAILURE";

export const GET_SINGLE_CLAIM_SUCCESS = "GET_SINGLE_CLAIM_SUCCESS";

export const REMOVE_CLAIM_FILE_SUCCESS = "REMOVE_CLAIM_FILE_SUCCESS";